# Configuración Spring Boot — Banco de Preguntas Saber Pro (Corte 2)
spring.application.name=banco-preguntas

# Puerto del servidor
server.port=8080

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method

# Configuración de Logging
logging.level.co.unicauca.iso2.bancopreguntas=INFO
